# Generated by Django 2.2.4 on 2019-08-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todolist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
